### PR TITLE
adds the option to export the key of the element

### PR DESCRIPTION
**Pull request by mkl87**

### CODE REVIEW

**Comment by utom** [comment]
I do not know what is the key name and for what purposes?

**Comment by mkl87** [comment]
Hi,

we create Applications for ios Android and Windows and needed a way how our
designers can specify the key value for a TextView. So now all developers
can use the exportet name.

Best regards
Michael

Am 05.10.2016 5:34 nachm. schrieb "utom" <notifications@github.com>:

**Comment by mkl87** [comment]
Any update?

**Comment by utom** [comment]
Sorry, I really understand what is the key name? how can I get the key and value in Sketch layer?

**Comment by mkl87** [comment]
I created a short description. Just let me know if the workflow is still unclear.

https://www.dropbox.com/s/6dbqvd4628kx4x7/infos.png?dl=0

**Comment by mkl87** [comment]
Any update?

**Comment by utom** [comment]
I think the key-name must save on layer, and how to save... I need time to think

**Comment by mkl87** [comment]
Any update?

**Comment by mkl87** [comment]
I merged your changes to my pull-request. Please accept the pull-request or add some helpful comments why you don't like to merge the request.

**Pull request merged**
