### PR TITLE
Percentage Positions & Sizing

### PR DESCRIPTION
**Pull request by kylelol**
Added an extra option to calculate position and sizing in percentages. 

The shortcut is ctrl + shift + q, and ctrl + shift + w. 

*note: I intend to do this for sizes too.

### CODE REVIEW

**Comment by kylelol** [comment]
Thanks ! Would you like me to update the readme as well ?

**Comment by utom** [comment]
Thank you so much!  but "Percentage" has something wrong.

MOVE to branch "beta” and REMOVE "Percentage" on branch "master"

:D

**Comment by kylelol** [comment]
Do you know what specifically is off? 


—

**Comment by utom** [comment]
https://github.com/utom/sketch-measure/commit/ddd2e4ff4313f3830c7f30a23892364dd5d866c0

**Comment by kylelol** [comment]
Do you think is because the frame of the artboard is not being converted to the correct units in the percent algorithm? 


—

**Comment by kylelol** [comment]
It worked fine for me using 1x pts. 


—

**Comment by utom** [comment]
1x is working fine~ but 1.5x, 2x and 3x ?

```var scale = 2, width = 216, artboard = 720;
length = width / scale; // (216 / 720 = 108)
percent  = scale / artboard; // (108 / 720 = 0.15) <- 15%```

**Comment by kylelol** [comment]
is the pseudo code you posted above a solution? 

I think that seems to be my issue, i’m not accounting for the scale. 


—

**Comment by utom** [comment]
1x is working fine~ but 1.5x, 2x and 3x ?

WRONG
```
var scale = 2, width = 216, artboard = 720;
length = width / scale; // (216 / 720 = 108)
percent  = length / artboard; // (108 / 720 = 0.15) <- 15%
```

RIGHT
```
var scale = 2, width = 216, artboard = 720;
percent  = width / artboard; // (216 / 720 = 0.3) <- 30%
```

**Comment by kylelol** [comment]
awesome thanks for the quick replies! I’ll get to fixing it.




I’m a bit new to github workflow, should I just continue to make changes on my branch then create a new pull request? 


—

**Comment by utom** [comment]
awesome! Could you pull request on branch "beta"? :+1:

**Comment by kylelol** [comment]
Will do ! 


—

**Comment by kylelol** [comment]
Ok submitted the pull request ! 


—

**Pull request merged**
